[tool.ruff]
line-length=150
# "B006": Disallow mutable default arguments
lint.extend-select = ["B006"]

[tool.ruff.lint.per-file-ignores]
# "F403": Unused import
# "F405": * Import
"configuration/settings.py" = ["F403", "F405"]

[tool.q2.check.ignores]
example_check = false
